version: '3.8'

services:
  mysql:
    image: mysql:8.3.0-oracle
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - minha-net

  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - mysql
    networks:
      - minha-net

networks:
  minha-net:
    driver: bridge

volumes:
  mysql-data:
